### PR TITLE
Update to 2.5.0

### PR DESCRIPTION
**Pull request by cbouss**
Changes:
- Update to 2.5.0

https://github.com/libexpat/libexpat/blob/R_2_5_0/expat/Changes
Changes in source code, no change to the public interface. (i.e. no rebuilds needed)

https://github.com/libexpat/libexpat/tree/R_2_5_0

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM.

Do we need the `libexpat` output like conda-forge did https://github.com/conda-forge/expat-feedstock/blob/ad055e3aaea632237c7b4755f28fa3ee57913540/recipe/meta.yaml#L29?

**Review by JeanChristopheMorinPerso — APPROVED** [review]

**Comment by JeanChristopheMorinPerso** [comment]
There is a slight change in SO versions, but at least the major isn't changed.
Before:
```
libexpat.1.8.9.dylib
libexpat.1.dylib -> libexpat.1.8.9.dylib
libexpat.a
libexpat.dylib -> libexpat.1.8.9.dylib
```
After:
```
libexpat.1.8.10.dylib
libexpat.1.dylib -> libexpat.1.8.10.dylib
libexpat.a
libexpat.dylib -> libexpat.1.8.10.dylib
```

In theory, if nothing links directly to `libexpat.1.8.9.dylib` (which should be the case) we should be good.

**Comment by cbouss** [comment]
> LGTM.
> 
> Do we need the `libexpat` output like conda-forge did https://github.com/conda-forge/expat-feedstock/blob/ad055e3aaea632237c7b4755f28fa3ee57913540/recipe/meta.yaml#L29?

Good question. I think we should define some kind of policy before doing these kind of changes.

**Comment by cbouss** [comment]
> There is a slight change in SO versions, but at least the major isn't changed. Before:
> 
> ```
> libexpat.1.8.9.dylib
> libexpat.1.dylib -> libexpat.1.8.9.dylib
> libexpat.a
> libexpat.dylib -> libexpat.1.8.9.dylib
> ```
> 
> After:
> 
> ```
> libexpat.1.8.10.dylib
> libexpat.1.dylib -> libexpat.1.8.10.dylib
> libexpat.a
> libexpat.dylib -> libexpat.1.8.10.dylib
> ```
> 
> In theory, if nothing links directly to `libexpat.1.8.9.dylib` (which should be the case) we should be good.

The last update was similar, and no issues got reported, so we should still be good.

**Pull request merged**
